// Date: 3/22/2015 12:02:28 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.aggro.asma.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelUFO extends ModelBase
{
  //fields
    ModelRenderer dome;
    ModelRenderer body;
    ModelRenderer body2;
    ModelRenderer body3;
    ModelRenderer body4;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
  
  public ModelUFO()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      dome = new ModelRenderer(this, 0, 0);
      dome.addBox(-3F, -3F, -3F, 6, 6, 6);
      dome.setRotationPoint(0F, 15F, -3F);
      dome.setTextureSize(64, 64);
      dome.mirror = true;
      setRotation(dome, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 12);
      body.addBox(-3.5F, 3F, -3.5F, 7, 1, 7);
      body.setRotationPoint(0F, 15F, -3F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      body3 = new ModelRenderer(this, 0, 20);
      body3.addBox(-4F, 4F, -4F, 8, 1, 8);
      body3.setRotationPoint(0F, 15F, -3F);
      body3.setTextureSize(64, 64);
      body3.mirror = true;
      setRotation(body3, 0F, 0F, 0F);
      body2 = new ModelRenderer(this, 0, 29);
      body2.addBox(-4.466667F, 5F, -3.466667F, 9, 1, 9);
      body2.setRotationPoint(0F, 15F, -4F);
      body2.setTextureSize(64, 64);
      body2.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      body4 = new ModelRenderer(this, 0, 39);
      body4.addBox(-5F, 6F, -5F, 10, 1, 10);
      body4.setRotationPoint(0F, 15F, -3F);
      body4.setTextureSize(64, 64);
      body4.mirror = true;
      setRotation(body4, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 6, 0);
      leg1.addBox(2F, 7F, -4F, 2, 1, 2);
      leg1.setRotationPoint(0F, 15F, -3F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 6, 0);
      leg2.addBox(-4F, 7F, -4F, 2, 1, 2);
      leg2.setRotationPoint(0F, 15F, -3F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 6, 0);
      leg3.addBox(-4F, 7F, 2F, 2, 1, 2);
      leg3.setRotationPoint(0F, 15F, -3F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 6, 0);
      leg4.addBox(2F, 7F, 2F, 2, 1, 2);
      leg4.setRotationPoint(0F, 15F, -3F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    dome.render(f5);
    body.render(f5);
    body3.render(f5);
    body2.render(f5);
    body4.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
