// Date: 3/22/2015 5:26:31 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.aggro.asma.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelLakitu extends ModelBase
{
  //fields
    ModelRenderer hair1;
    ModelRenderer hair;
    ModelRenderer head;
    ModelRenderer dome;
    ModelRenderer shell;
    ModelRenderer lefty;
    ModelRenderer righty;
    ModelRenderer leftleg;
    ModelRenderer rightleg;
  
  public ModelLakitu()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      hair1 = new ModelRenderer(this, 0, 9);
      hair1.addBox(-4F, -11F, 0F, 8, 8, 1);
      hair1.setRotationPoint(0F, 7F, 0F);
      hair1.setTextureSize(64, 64);
      hair1.mirror = true;
      setRotation(hair1, 0F, 0.7853982F, 0F);
      hair = new ModelRenderer(this, 0, 0);
      hair.addBox(-4F, -11F, 0F, 8, 8, 1);
      hair.setRotationPoint(0F, 7F, 0F);
      hair.setTextureSize(64, 64);
      hair.mirror = true;
      setRotation(hair, 0F, -0.7853982F, 0F);
      head = new ModelRenderer(this, 0, 18);
      head.addBox(-3F, -3F, -3F, 6, 6, 6);
      head.setRotationPoint(0F, 7F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      dome = new ModelRenderer(this, 0, 30);
      dome.addBox(-4F, -4F, -4F, 8, 8, 8);
      dome.setRotationPoint(0F, 7F, 0F);
      dome.setTextureSize(64, 64);
      dome.mirror = true;
      setRotation(dome, 0F, 0F, 0F);
      shell = new ModelRenderer(this, 0, 49);
      shell.addBox(-3F, 0F, -2F, 6, 8, 7);
      shell.setRotationPoint(0F, 10F, 0F);
      shell.setTextureSize(64, 64);
      shell.mirror = true;
      setRotation(shell, 0F, 0F, 0F);
      lefty = new ModelRenderer(this, 24, 18);
      lefty.addBox(0F, 0F, 0F, 2, 6, 2);
      lefty.setRotationPoint(3F, 10F, -2F);
      lefty.setTextureSize(64, 64);
      lefty.mirror = true;
      setRotation(lefty, 0F, 0F, 0F);
      righty = new ModelRenderer(this, 24, 18);
      righty.addBox(-2F, 0F, 0F, 2, 6, 2);
      righty.setRotationPoint(-3F, 10F, -2F);
      righty.setTextureSize(64, 64);
      righty.mirror = true;
      setRotation(righty, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 24, 18);
      leftleg.addBox(0F, 0F, 0F, 2, 6, 2);
      leftleg.setRotationPoint(1F, 18F, -2F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 24, 18);
      rightleg.addBox(-2F, 0F, 0F, 2, 6, 2);
      rightleg.setRotationPoint(-1F, 18F, -2F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    hair1.render(f5);
    hair.render(f5);
    head.render(f5);
    dome.render(f5);
    shell.render(f5);
    lefty.render(f5);
    righty.render(f5);
    leftleg.render(f5);
    rightleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
    this.rightleg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
    this.leftleg.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
    this.rightleg.rotateAngleY = 0.0F;
    this.leftleg.rotateAngleY = 0.0F;
    
  }

}
