// Date: 3/19/2015 5:07:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.aggro.asma.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import com.aggro.asma.entity.EntityHand;

public class ModelHand extends ModelBase
{
  //fields
    ModelRenderer wrist;
    ModelRenderer palm;
    ModelRenderer pinky;
    ModelRenderer ring;
    ModelRenderer index;
    ModelRenderer middle;
    ModelRenderer thumb;
  
  public ModelHand()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      wrist = new ModelRenderer(this, 0, 0);
      wrist.addBox(-4F, -8F, -4F, 8, 8, 8);
      wrist.setRotationPoint(0F, -1F, 0F);
      wrist.setTextureSize(64, 64);
      wrist.mirror = true;
      setRotation(wrist, 0F, 0F, 0F);
      palm = new ModelRenderer(this, 24, 16);
      palm.addBox(-6F, 0F, -2F, 12, 12, 4);
      palm.setRotationPoint(0F, 0F, 0F);
      palm.setTextureSize(64, 64);
      palm.mirror = true;
      setRotation(palm, 0F, 0F, 0F);
      pinky = new ModelRenderer(this, 0, 16);
      pinky.addBox(-2F, -12F, -2F, 3, 12, 3);
      pinky.setRotationPoint(4F, 12F, 1F);
      pinky.setTextureSize(64, 64);
      pinky.mirror = true;
      setRotation(pinky, 0.2230717F, 3.141593F, 0F);
      ring = new ModelRenderer(this, 0, 16);
      ring.addBox(-1F, -12F, -2F, 3, 12, 3);
      ring.setRotationPoint(2F, 12F, 1F);
      ring.setTextureSize(64, 64);
      ring.mirror = true;
      setRotation(ring, 0.4089647F, 3.141593F, 0F);
      index = new ModelRenderer(this, 0, 16);
      index.addBox(-2F, 0F, -2F, 3, 12, 3);
      index.setRotationPoint(-4F, 12F, 0F);
      index.setTextureSize(64, 64);
      index.mirror = true;
      setRotation(index, 0F, 0F, 0F);
      middle = new ModelRenderer(this, 0, 16);
      middle.addBox(-2F, 0F, -2F, 3, 12, 3);
      middle.setRotationPoint(-1F, 12F, 0F);
      middle.setTextureSize(64, 64);
      middle.mirror = true;
      setRotation(middle, 0F, 0F, 0F);
      thumb = new ModelRenderer(this, 12, 16);
      thumb.addBox(0F, 0F, 0F, 3, 7, 3);
      thumb.setRotationPoint(-7F, 0F, 1F);
      thumb.setTextureSize(64, 64);
      thumb.mirror = true;
      setRotation(thumb, 0.3717861F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    wrist.render(f5);
    palm.render(f5);
    pinky.render(f5);
    ring.render(f5);
    index.render(f5);
    middle.render(f5);
    thumb.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
	  if (entity.onGround){
	  this.index.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
      this.middle.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
      this.index.rotateAngleY = 0.0F;
      this.middle.rotateAngleY = 0.0F;
      index.setRotationPoint(-4F, 12F, 0F);
      middle.setRotationPoint(-1F, 12F, 0F);
      setRotation(palm, 0.0F, 0.0F, 0.0F);
      setRotation(wrist, 0.0F, 0.0F, 0.0F);
      ring.setRotationPoint(2F, 12F, 1F);
      setRotation(ring, 0.4089647F, 3.141593F, 0F);
      pinky.setRotationPoint(4F, 12F, 1F);
      setRotation(pinky, 0.2230717F, 3.141593F, 0F);
      }
	  else{
      this.index.setRotationPoint(-4F, 1F, -10F);
      setRotation(index, -89.6F, 0.0F, 0.0F);
      this.middle.setRotationPoint(-1F, 1F, -10F);
      setRotation(middle, -89.7F, 0.0F, 0.0F);
      setRotation(palm, 180.7F, 0.0F, 0.0F);
      setRotation(wrist, -95.7F, 0.0F, 0.0F);
      this.ring.setRotationPoint(2F, 1F, -22F);
      setRotation(ring, -89.5F, 0.0F, 0.0F);
      this.pinky.setRotationPoint(5F, 1F, -22F);
      setRotation(pinky, -89.4F, 0.0F, 0.0F);
      }
	  
	  if (entity.isBurning()){
	      this.index.setRotationPoint(-4F, 1F, -10F);
	      setRotation(index, -90.0F, 0.0F, 0.0F);
	      this.middle.setRotationPoint(-1F, 1F, -10F);
	      setRotation(middle, 0.0F, 0.0F, 0.0F);
	      setRotation(palm, 180.7F, 0.0F, 0.0F);
	      setRotation(wrist, -95.7F, 0.0F, 0.0F);
	      this.ring.setRotationPoint(2F, 1F, -10F);
	      setRotation(ring, 90.0F, 0.0F, 0.0F);
	      this.pinky.setRotationPoint(5F, 1F, -10F);
	      setRotation(pinky, -90.0F, 0.0F, 0.0F);
	      }
  }

}
