// Date: 9/20/2015 3:54:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.DwainEdwards.Blocks;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelATM extends ModelBase {
	// fields
	ModelRenderer Bottom;
	ModelRenderer Screen;
	ModelRenderer Keyboard;
	ModelRenderer Top;
	ModelRenderer Right;
	ModelRenderer Left;

	public ModelATM() {
		textureWidth = 256;
		textureHeight = 128;

		Bottom = new ModelRenderer(this, 0, 0);
		Bottom.addBox(-8F, 0F, -8F, 16, 14, 16);
		Bottom.setRotationPoint(0F, 10F, 0F);
		Bottom.setTextureSize(256, 128);
		Bottom.mirror = true;
		setRotation(Bottom, 0F, 0F, 0F);
		Screen = new ModelRenderer(this, 0, 36);
		Screen.addBox(-7F, 0F, 0F, 12, 11, 8);
		Screen.setRotationPoint(1F, -1F, 0F);
		Screen.setTextureSize(256, 128);
		Screen.mirror = true;
		setRotation(Screen, 0F, 0F, 0F);
		Keyboard = new ModelRenderer(this, 0, 62);
		Keyboard.addBox(0F, 0F, 0F, 12, 2, 5);
		Keyboard.setRotationPoint(-6F, 9F, -5F);
		Keyboard.setTextureSize(256, 128);
		Keyboard.mirror = true;
		setRotation(Keyboard, 0F, 0F, 0F);
		Top = new ModelRenderer(this, 52, 38);
		Top.addBox(-8F, 0F, -8F, 16, 1, 16);
		Top.setRotationPoint(0F, -2F, 0F);
		Top.setTextureSize(256, 128);
		Top.mirror = true;
		setRotation(Top, 0F, 0F, 0F);
		Right = new ModelRenderer(this, 70, 0);
		Right.addBox(-8F, 0F, -8F, 2, 11, 16);
		Right.setRotationPoint(0F, -1F, 0F);
		Right.setTextureSize(256, 128);
		Right.mirror = true;
		setRotation(Right, 0F, 0F, 0F);
		Left = new ModelRenderer(this, 70, 0);
		Left.addBox(6F, 0F, -8F, 2, 11, 16);
		Left.setRotationPoint(0F, -1F, 0F);
		Left.setTextureSize(256, 128);
		Left.mirror = true;
		setRotation(Left, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Bottom.render(f5);
		Screen.render(f5);
		Keyboard.render(f5);
		Top.render(f5);
		Right.render(f5);
		Left.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void renderModel(Float f) {
		Bottom.render(f);
		Screen.render(f);
		Keyboard.render(f);
		Top.render(f);
		Right.render(f);
		Left.render(f);
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
